# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7129e08e89c0ec1a172e2e141444669deb4d540f3d70d95e7664a9150110ccb8b98961c8e4a6ef49fe97eaac2c1c5979858770f12906db5251700bf7fe5b8cd2

test:
  secret_key_base: 54a47e3bde02032c4c5bb862748abfb33354120511e034e467602b172ac73527152f4f2be7ca1eb5c2fcf8a6a58defc1541daba82760783b7e381bd3fb7df749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
